deploymentType: deployment

replicaCount: 1

image:
  repository: wiesslogia/gitops
  pullPolicy: IfNotPresent
  tag: "f14091618f8ac235abe5ac33ba79e4287fa094bd"

resources: 
  requests:
    cpu: "10m"
    memory: "50Mi"
  limits:
    cpu: "25m"
