deploymentType: deployment

replicaCount: 1

image:
  repository: wiesslogia/gitops
  pullPolicy: IfNotPresent
  tag: "6e60dedfb6a12dde310b60cedf89359cffd08047"

resources: 
  requests:
    cpu: "10m"
    memory: "50Mi"
  limits:
    cpu: "25m"
